# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/OLED_Design/OLED_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design || ORIG_REF_NAME==OLED_Design} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_processing_system7_0_0/OLED_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_processing_system7_0_0 || ORIG_REF_NAME==OLED_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_PmodOLED_0_0/OLED_Design_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_PmodOLED_0_0 || ORIG_REF_NAME==OLED_Design_PmodOLED_0_0} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_xbar_0/OLED_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_xbar_0 || ORIG_REF_NAME==OLED_Design_xbar_0} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_auto_pc_0/OLED_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_auto_pc_0 || ORIG_REF_NAME==OLED_Design_auto_pc_0} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_ps7_0_axi_periph_0/OLED_Design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==OLED_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OLED_Design/ip/OLED_Design_rst_ps7_0_100M_0/OLED_Design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==OLED_Design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/ozratzon/test/test.gen/sources_1/bd/OLED_Design/OLED_Design_ooc.xdc
